--- #YAML:1.0
name:               WWW-Curl
version:            4.19_9903
abstract:           Perl extension interface for libcurl
author:
    - Cris Bailiff <c.bailiff+curl at devsecure.com>
    - Balint Szilakszi <szbalint at cpan.org>
license:            MPL or MIT/X-derivate
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    perl:  5.006001
resources:
    repository:  http://github.com/szbalint/WWW--Curl
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
